import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { SessionProvider } from "next-auth/react";
import { AuthErrorHandler } from "@/components/auth/auth-error-handler";
import { Toaster } from "@/components/ui/sonner";
import { VideoCallProvider } from "@/context/VideoCallContext";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if (typeof window !== 'undefined') {
                const originalRemoveChild = Node.prototype.removeChild;
                Node.prototype.removeChild = function(child) {
                  if (child.parentNode !== this) {
                    if (console) console.warn('Hydration mismatch prevented: Cannot remove a child from a different parent', child, this);
                    return child;
                  }
                  return originalRemoveChild.apply(this, arguments);
                };
                const originalInsertBefore = Node.prototype.insertBefore;
                Node.prototype.insertBefore = function(newNode, referenceNode) {
                  if (referenceNode && referenceNode.parentNode !== this) {
                    if (console) console.warn('Hydration mismatch prevented: Cannot insert before a reference node from a different parent', referenceNode, this);
                    return newNode;
                  }
                  return originalInsertBefore.apply(this, arguments);
                };
              }
            `,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <SessionProvider refetchInterval={0} refetchOnWindowFocus={false}>
          <VideoCallProvider>
            <AuthErrorHandler />
            <NextTopLoader color="var(--primary)" showSpinner={false} />
            {children}
            <Toaster position="top-right" richColors />
          </VideoCallProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
