import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { SessionProvider } from "next-auth/react";
import { AuthErrorHandler } from "@/components/auth/auth-error-handler";
import { Toaster } from "@/components/ui/sonner";
import { VideoCallProvider } from "@/context/VideoCallContext";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <SessionProvider refetchInterval={0} refetchOnWindowFocus={false}>
          <VideoCallProvider>
            <AuthErrorHandler />
            <NextTopLoader color="var(--primary)" showSpinner={false} />
            {children}
            <Toaster position="top-right" richColors />
          </VideoCallProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
